-- most_popular_transport_types
SELECT JOURNEY_TYPE, SUM(JOURNEYS_MILLIONS) AS TOTAL_JOURNEYS_MILLIONS
FROM TFL.JOURNEYS
GROUP BY JOURNEY_TYPE
ORDER BY TOTAL_JOURNEYS_MILLIONS DESC;

-- emirates_airline_popularity
SELECT MONTH, YEAR, ROUND(SUM(JOURNEYS_MILLIONS), 2) AS ROUNDED_JOURNEYS_MILLIONS
FROM TFL.JOURNEYS
WHERE JOURNEYS.JOURNEY_TYPE = 'Emirates Airline'
GROUP BY MONTH, YEAR 
ORDER BY ROUNDED_JOURNEYS_MILLIONS DESC
LIMIT 5;

-- least_popular_years_tube
SELECT YEAR, 'Underground & DLR' AS JOURNEY_TYPE, SUM(JOURNEYS_MILLIONS) AS TOTAL_JOURNEYS_MILLIONS
FROM TFL.JOURNEYS
WHERE JOURNEYS.JOURNEY_TYPE = 'Underground & DLR'
GROUP BY YEAR
ORDER BY TOTAL_JOURNEYS_MILLIONS ASC
LIMIT 5;